# Enhanced NIA Configuration with Multi-Provider LLM Support and Database Integration

# Voice Interface Settings
voice:
  hotkey: "space"
  tts_engine: "pyttsx3"
  tts_rate: 165
  tts_voice_id: null
  chunk_chars_min: 60
  chunk_chars_max: 240
  sentence_boundary_regex: "[.!?…]+\\s"

# Hybrid listening configuration
hybrid:
  passive_enabled: false
  wake_words:
    - "nia"
    - "hey nia"
    - "okay nia"
    - "buddy"
    - "hey buddy"

# Speech-to-Text and Voice Activity Detection
stt:
  engine: "vosk"
  vosk_model_path: "model/vosk-model-small-en-us-0.15"
  vad: false
  vad_engine: "silero"
  vad_aggressiveness: 2
  vad_trigger_ms: 250
  vad_release_ms: 300
  deepfilternet: true
  deepfilternet_model_dir: "deepfilternet2"

# Enhanced Brain (LLM) settings with Multi-Provider Support
brain:
  # Primary LLM Provider Configuration
  provider: "openai"  # Options: "ollama", "openai", "anthropic"
  model: "gpt-4o-mini"
  
  # Provider-specific configuration
  provider_config:
    # OpenAI specific settings
    api_key: "${OPENAI_API_KEY}"  # Set via environment variable
    # base_url: "https://api.openai.com/v1"  # Optional custom endpoint
    # organization: "your-org-id"  # Optional
    
    # Anthropic specific settings (when using Anthropic)
    # api_key: "${ANTHROPIC_API_KEY}"
    
    # Ollama specific settings (when using Ollama)
    # base_url: "http://localhost:11434"
  
  # Fallback providers (tried in order if primary fails)
  fallback_providers:
    - provider: "ollama"
      model: "qwen3:4b"
      config:
        base_url: "http://localhost:11434"
    - provider: "anthropic"
      model: "claude-3-5-haiku-20241022"
      config:
        api_key: "${ANTHROPIC_API_KEY}"
  
  # Global LLM settings
  temperature: 0.7
  max_tokens: 2000
  timeout_s: 180
  
  # Legacy settings (maintained for backward compatibility)
  system_prompt: "You are NIA, a helpful and friendly voice assistant. Keep your responses concise and conversational. Speak naturally as if you're having a real conversation. Be warm, engaging, and helpful."
  transport: "http"
  stream: true
  cancel_on_barge_in: true

# Database Configuration (Enhanced)
database:
  # Primary database for structured data
  primary:
    type: "sqlite"  # Options: "sqlite", "postgresql", "mysql"
    connection:
      path: "data/nia.db"  # For SQLite
      # host: "localhost"   # For PostgreSQL/MySQL
      # port: 5432          # For PostgreSQL/MySQL
      # database: "nia"     # For PostgreSQL/MySQL
      # username: "${DB_USER}"
      # password: "${DB_PASSWORD}"
    
    # Connection pool settings (for PostgreSQL/MySQL)
    pool:
      min_connections: 2
      max_connections: 20
      timeout: 30
  
  # Redis for caching and sessions (optional)
  cache:
    enabled: true
    type: "redis"  # Options: "redis", "memory"
    connection:
      host: "localhost"
      port: 6379
      db: 0
      password: "${REDIS_PASSWORD}"  # Optional
    
    # Cache settings
    default_ttl: 3600  # 1 hour
    max_memory: "100mb"

# Enhanced Memory Configuration
memory:
  enabled: true
  
  # Vector database settings (LanceDB)
  vector_db:
    type: "lancedb"
    path: "data/memory"
    collection: "conversations"
    embedding_model: "nomic-embed-text"
    enable_embeddings: true
    
    # Vector search settings
    max_recent_queries: 5
    min_similarity_score: 0.7
    index_metric: "cosine"
  
  # Structured memory storage
  structured_db:
    enabled: true
    store_metadata: true
    index_content: true
    retention_days: 365  # Keep memories for 1 year

# Enhanced Knowledge Management
knowledge:
  enabled: true
  
  # Vector-based knowledge storage
  vector_store:
    type: "lancedb"
    path: "data/knowledge"
    collection: "documents"
    embedding_model: "nomic-embed-text"
    top_k: 5
  
  # Structured knowledge database
  structured_db:
    enabled: true
    auto_categorize: true
    enable_search_index: true
  
  # Knowledge sources configuration
  sources:
    - type: "file"
      path: "data/knowledge/docs"
      formats: ["txt", "md", "pdf"]
      auto_sync: true
    - type: "web"
      enabled: false
      urls: []
      sync_interval: 3600

# User Management (New)
users:
  enabled: false  # Enable for multi-user support
  authentication:
    type: "simple"  # Options: "simple", "oauth", "ldap"
    session_duration: 86400  # 24 hours
  
  profiles:
    store_preferences: true
    personalization: true

# Analytics and Monitoring (New)
analytics:
  enabled: true
  
  # Usage tracking
  track_interactions: true
  track_performance: true
  retention_days: 90
  
  # Privacy settings
  anonymize_data: true
  store_content: false  # Don't store conversation content in analytics

# API Configuration (New)
api:
  enabled: true
  host: "localhost"
  port: 8080
  
  # Authentication
  require_auth: false
  api_keys:
    enabled: false
    keys: []
  
  # Rate limiting
  rate_limit:
    enabled: true
    requests_per_minute: 60
    burst_size: 10

# Backup and Recovery (New)
backup:
  enabled: true
  
  # Automatic backups
  schedule: "daily"  # Options: "hourly", "daily", "weekly"
  retention_count: 30
  
  # Backup targets
  local:
    enabled: true
    path: "backups/"
  
  cloud:
    enabled: false
    provider: "s3"  # Options: "s3", "gcs", "azure"
    # Configuration specific to provider
    config: {}

# Legacy settings (maintained for backward compatibility)
autonomy:
  enabled: true
  suggestion_interval_s: 90
  confidence_threshold: 0.6
  use_memory: true
  max_memory_snippets: 5
  
  confirm_before_speaking: true
  confirm_prompt: "I have a suggestion that might help—would you like to hear it?"
  confirm_yes_keywords: ["yes", "sure", "okay", "go ahead", "please", "sounds good"]
  confirm_no_keywords: ["no", "not now", "later", "skip", "dismiss"]
  confirm_timeout_s: 4
  
  decision_keywords:
    - "should i"
    - "what if"
    - "maybe"
    - "i think"
    - "i'm not sure"
    - "help me decide"
  
  high_value_topics:
    - "work"
    - "project"
    - "meeting"
    - "deadline"
    - "plan"
    - "schedule"
    - "task"
    - "problem"
    - "issue"
    - "decision"